### ISSUE TITLE
Integrated Projects & Rules

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#2001]
**Task:**
- Need to update the Projects section (https://thenewboston.com/projects) with an updated design.

**Design:**
- https://www.figma.com/file/5madc2zFyUi7A3G0ZeFcry/Integrated-Projects-and-Rules?node-id=0%3A1

Feel free to break the task into smaller sub-tasks. Let me know if any additional information or clarification is required.

**Comment by jamessspanggg** [comment]
I think we basically have to move the projects page to be under the developer portal section. @thesanjeevsharma 

The implementations should be quite similar with the existing one, except for the sidemenu where the `Approved Projects` section does not scroll accordingly. When we click one of the links in the sidemenu, it will directly visit the project details page. Only the inner subsections need to highlight and scroll accordingly.

I think we can break down the tasks to:
- [ ] Move Projects Home Page 
- [ ] Move Projects Details Page
- [ ] Move List of Projects
- [ ] Move Rules and Guidelines page
