### ISSUE TITLE
Landing Page V2

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#333]
- [ ] Update main header message to 'Open-source community for creators' (all **bold**)
- [ ] Update main subtext to 'Learn to code, collaborate on projects, gain experience, build a community, and earn coins by contributing.'
- [ ] Remove images of the app & replace it with the illustration attached to the ticket
- [ ] Change background color of the 3-step block to Sail **Blue** 900 (#131F41)
- [ ] Link colors in 3-step block is Sail **Blue** 300 (#7DABF8)
- [ ] On the 3rd step, change the wording 'Earn Points' to 'Earn Coins'
- [ ] Remove 'INSTANT TRANSACTIONS' text completely
- [ ] Update 'Say goodbye too...' text to 'About our digital currency' 
- [ ] Update to bitcoin/thenewboston cards to use the color (#556CD6) as the dropshadow. 
- [ ] In the bitcoin/thenewboston cards, change the wording from 'avg. tx time' to 'avg. block time' 
- [ ] thenewboston logo on the header as well as the thenewboston card is wrong, please update it with the logo on the footer. That is the correct logo. Logo also must be 30px size. 
- [ ] Change the footer color to Sail **Blue** 900 (#131F41)

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=6%3A0

**IMAGE:**
[Web Design.png.zip](https://github.com/thenewboston-developers/Website/files/5463069/Web.Design.png.zip)

**Comment by aayushi14** [comment]
I think 2nd point should have **by** instead of **for**: 
Update main subtext to 'Learn to code, collaborate on projects, gain experience, build a community, and earn coins **by** contributing.'

**Comment by aayushi14** [comment]
Can you assign this to me?

**Comment by kristykjlee** [comment]
@aayushi14 You got it! All yours

**Comment by angle943** [comment]
@aayushi14 btw, you no longer need to ask for assignment. We've recently changed to take more of a first-come first-serve approach

**Comment by angle943** [comment]
@aayushi14 Paid! thanks you :D
